### ISSUE TITLE
spec file has extra unneeded characters

### ISSUE THREAD

**Issue by cookie33** [sara-nl/irods-msi-persistent-id#1]
The spec file has:
```
%if "%{irodsversion}" == "4.1.11"
%define irods_msi_path /var/lib/irods/plugins/microservices/
%else
%define irods_msi_path /usr/lib/irods/plugins/microservices/
%endif
```

I would remove the "/" at the end of the lines and make it:
```
%if "%{irodsversion}" == "4.1.11"
%define irods_msi_path /var/lib/irods/plugins/microservices
%else
%define irods_msi_path /usr/lib/irods/plugins/microservices
%endif
```

This because the "/" are used in the specific itself.

**Comment by stefan-wolfsheimer** [comment]
@cookie33 I have fixed this.
I wonder if it actually matters. The double slashes are used in paths which are normalized anyways. Do you know an example / case were this is crucial ?
