### ISSUE TITLE
two template files. Which one to use and please order alphabetically inside.

### ISSUE THREAD

**Issue by cookie33** [sara-nl/irods-msi-persistent-id#2]
Hi,

We have two template files:
 * irods_pid.json.template
 * irods_pid.json.template_2

The documentation is not clear which one to use. I will use the `irods_pid.json.template_2`

The order in the template should be as follows for readability (sorted alphabetically):
* handle
* irods
* lookup

**Comment by stefan-wolfsheimer** [comment]
While I agree that it is better to use consistent order of sections in the configuration file, I think it is better to put the handle section at the end.
- irods
- lookup
- handle

The handle configuration is usually the most complex substructure and thus it is more readable to put it at the end.
